### ISSUE TITLE
Remove AddHive behaviour.

### ISSUE THREAD

**Issue by robertoloja** [pwestman/SmartHive#2]
The RPi should add itself to the database, once the user has (somehow) logged into their google account (RPi runs a webserver?), then shows up on the app. This should be the only way (other than debug scripts) to add a hive.

**Comment by n01060890** [comment]
How about the RPi is always running, and submitting the data to the DB. It has unique name/pass in order  for user to add it.  It also means that few users can track same hive, if they have credentials to it.
